### ISSUE TITLE
bug: E-6 Unable to Sync, this folder is in special condition, thus can't Sync directly. An auto-fix has b

### ISSUE THREAD

**Issue by qiuqiao** [tiddly-gittly/TidGi-Desktop#163]
## Environment

TidGi 0.7.2-prerelease4
Electron 15.3.0
win32 10.0.19042
Locale: zh-CN

## Description:

之前说的没有保存到main分支下的问题，在更新且确认设置里写了main分支之后依旧会报错
![tmp587A](https://user-images.githubusercontent.com/53331340/147496591-593c765a-4045-49db-8e2b-6b3cf2a958a9.png)

## Additional Context

```typescript
CantSyncInSpecialGitStateAutoFixFailed: E-6 Unable to Sync, this folder is in special condition, thus can't Sync directly. An auto-fix has been tried, but error still remains. Please resolve all the conflict manually (For example, use VSCode to open the wiki folder), if this still don't work out, please use professional Git tools (Source Tree, GitKraken) to solve this. This is caused by procedural bug in the git-sync-js.
rebaseContinueStdError when |DIRTY: fatal: No rebase in progress?

commitStdError when |DIRTY: 
fatal: No rebase in progress?

    at Qr (C:\Users\QQ\AppData\Local\TidGi\app-0.7.2-prerelease4\resources\app.asar.unpacked\.webpack\main\webpack:\TidGi\node_modules\git-sync-js\dist\sync.js:67:19)
    at process.RebaseSucceed (node:internal/process/task_queues:96:5)
    at C:\Users\QQ\AppData\Local\TidGi\app-0.7.2-prerelease4\resources\app.asar.unpacked\.webpack\main\webpack:\TidGi\node_modules\git-sync-js\dist\index.js:160:37
```

---

**Comment by linonetwo** [comment]
下一个 github desktop，看看当前 git 的状态截图看看吧

现在也不知道发生了啥
