### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by pengchzn** [tiddly-gittly/TidGi-Desktop#196]
## Environment

TidGi 0.7.6-prerelease2
Electron 17.0.1
win32 10.0.22000
Locale: zh-CN

## Description:
[TidGi-2022-02-25.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/8139744/TidGi-2022-02-25.log)

## Steps to Reproduce:
创建新wiki时出现此问题

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"F:\\Leetcode","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://github.com/pengchzn/Leetcode'
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"F:\\Leetcode","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://github.com/pengchzn/Leetcode'

    at Pt (C:\Users\pengc\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5Csync.js:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at StartConfiguringGithubRemoteRepository (C:\Users\pengc\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CcommitAndSync.js:82:13)
    at Mt (C:\Users\pengc\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CinitGit.js:37:25)
```

---

**Comment by linonetwo** [comment]
奇怪了，为啥 "branch":"HEAD"

表单里你应该是填了 main 的对吧

**Comment by pengchzn** [comment]
对，填的是main

**Comment by linonetwo** [comment]
可能 token 没填？

**Comment by linonetwo** [comment]
最新版应该没问题了，给 https://github.com/tiddly-gittly/git-sync-js 加了不少单元测试。
