### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by guoe2005** [tiddly-gittly/TidGi-Desktop#197]
## Environment

TidGi 0.7.5
Electron 17.0.1
win32 10.0.19043
Locale: zh-CN

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\guoyi\\Desktop\\tidgi","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://gitlab.com/guoe2005/tidgi'
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\guoyi\\Desktop\\tidgi","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://gitlab.com/guoe2005/tidgi'

    at Pt (C:\Users\guoyi\AppData\Local\TidGi\app-0.7.5\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5Csync.js:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at StartConfiguringGithubRemoteRepository (C:\Users\guoyi\AppData\Local\TidGi\app-0.7.5\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CcommitAndSync.js:82:13)
    at Mt (C:\Users\guoyi\AppData\Local\TidGi\app-0.7.5\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CinitGit.js:37:25)
```

---

**Comment by linonetwo** [comment]
origin 那个，是不是填成 main 或者 master 比较好？

**Comment by linonetwo** [comment]
好像是 "branch":"HEAD" 的问题，改成 main 试试？
