### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by king-wq** [tiddly-gittly/TidGi-Desktop#198]
## Environment

TidGi 0.7.4
Electron 16.0.8
win32 10.0.19042
Locale: zh-CN

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"D:\\Notions\\TiGi\\Java","branch":"main","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: fatal: unable to access 'https://github.com/king-wq/Java/': Failed to connect to github.com port 443: Timed out
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"D:\\Notions\\TiGi\\Java","branch":"main","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: fatal: unable to access 'https://github.com/king-wq/Java/': Failed to connect to github.com port 443: Timed out

    at Pt (C:\Users\尹辉\AppData\Local\TidGi\app-0.7.4\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5Csync.js:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at StartConfiguringGithubRemoteRepository (C:\Users\尹辉\AppData\Local\TidGi\app-0.7.4\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CcommitAndSync.js:82:13)
    at Mt (C:\Users\尹辉\AppData\Local\TidGi\app-0.7.4\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CinitGit.js:37:25)
```

---

**Comment by linonetwo** [comment]
Failed to connect to github.com

可能创建时网不大好？

**Comment by king-wq** [comment]
> 无法连接到 github.com
> 
> 可能创建时网不大好？

应该是哈哈哈哈，谢谢您了哈！！

**Comment by linonetwo** [comment]
先建本地的玩玩，后续可以再同步上去的

**Comment by king-wq** [comment]
> 先建本地的玩玩，后续可以再同步上去的

对对，我这样弄了之后就好多了。谢谢您哈
