### ISSUE TITLE
bug: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 C:\Users\hlu\Desktop\TIDDLYWIKI\wiki [1;31mError execu

### ISSUE THREAD

**Issue by lh5210069** [tiddly-gittly/TidGi-Desktop#205]
## Environment

TidGi 0.7.6-prerelease2
Electron 17.0.1
win32 10.0.18363
Locale: zh-CN

## Additional Context

```typescript
Error: [1;31mError executing boot module $:/plugins/kixam/timeline/widget.timeline.js: {"code":"MODULE_NOT_FOUND","requireStack":["C:\\Users\\hlu\\AppData\\Local\\TidGi\\app-0.7.6-prerelease2\\resources\\node_modules\\@tiddlygit\\tiddlywiki\\boot\\boot.js","C:\\Users\\hlu\\AppData\\Local\\TidGi\\app-0.7.6-prerelease2\\resources\\app.asar.unpacked\\.webpack\\main\\543.index.worker.js"]}

node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module '$:/plugins/kixam/moment/moment.js'
Require stack:
- C:\Users\hlu\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js
- C:\Users\hlu\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:785:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.$tw.modules.execute (C:\Users\hlu\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:867:11)
    at require (C:\Users\hlu\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:826:24)
    at $:/plugins/kixam/timeline/widget.timeline.js:20:16
    at $:/plugins/kixam/timeline/widget.timeline.js:652:3
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)[0m

    at Object.next (C:\Users\hlu\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Csrc%5Cservices%5Cwiki%5Cindex.ts:161:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

---

**Comment by linonetwo** [comment]
Cannot find module '$:/plugins/kixam/moment/moment.js'
