### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by appdev** [tiddly-gittly/TidGi-Desktop#209]
## Environment

TidGi 0.7.5
Electron 17.0.1
darwin 21.3.0
Locale: zh-CN

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"/Users/lengyue/Documents/wiki/wiki/wiki","remoteUrl":"https://github.com/appdev/notes","syncImmediately":true,"userInfo":{"gitUserName":"appdev","email":"lengyue@apkdv.com","accessToken":"gho_n8dp363EkcG4hlk9F...","branch":"main"},"defaultGitInfo":{"email":"tiddlygit@gmail.com","gitUserName":"tidgi","branch":"main","remote":"origin"},"logger":{}}.
errorMessages: Rebasing (1/2)
Rebasing (2/2)
error: could not apply 94d5664... Commit with Git-Sync-JS
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 94d5664... Commit with Git-Sync-JS
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"/Users/lengyue/Documents/wiki/wiki/wiki","remoteUrl":"https://github.com/appdev/notes","syncImmediately":true,"userInfo":{"gitUserName":"appdev","email":"lengyue@apkdv.com","accessToken":"gho_n8dp363EkcG4hlk9F...","branch":"main"},"defaultGitInfo":{"email":"tiddlygit@gmail.com","gitUserName":"tidgi","branch":"main","remote":"origin"},"logger":{}}.
errorMessages: Rebasing (1/2)
Rebasing (2/2)
error: could not apply 94d5664... Commit with Git-Sync-JS
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 94d5664... Commit with Git-Sync-JS

    at Ct (/private/var/folders/50/d4kvl0zx7q739hq6b9pt42180000gn/T/AppTranslocation/80345833-20A6-4C08-8B04-34951C876F38/d/TidGi.app/Contents/Resources/app.asar.unpacked/.webpack/main/file:/Users/runner/work/TidGi-Desktop/TidGi-Desktop/node_modules/git-sync-js/dist/src/commitAndSync.js:138:23)
    at process.StartConfiguringGithubRemoteRepository (node:internal/process/task_queues:96:5)
    at Mt (/private/var/folders/50/d4kvl0zx7q739hq6b9pt42180000gn/T/AppTranslocation/80345833-20A6-4C08-8B04-34951C876F38/d/TidGi.app/Contents/Resources/app.asar.unpacked/.webpack/main/file:/Users/runner/work/TidGi-Desktop/TidGi-Desktop/node_modules/git-sync-js/dist/src/initGit.js:37:25)
```

---

**Comment by linonetwo** [comment]
## Steps to Reproduce:
