### ISSUE TITLE
bug: [1;31mError executing boot module $:/plugins/linonetwo/smart-field/form.js: {"code":"MODULE_NOT_FOU

### ISSUE THREAD

**Issue by lh5210069** [tiddly-gittly/TidGi-Desktop#223]
## Environment

TidGi 0.7.7-prerelease2
Electron 18.0.1
win32 10.0.18363
Locale: zh-CN

## Additional Context

```typescript
Error: [1;31mError executing boot module $:/plugins/linonetwo/smart-field/form.js: {"code":"MODULE_NOT_FOUND","requireStack":["C:\\Users\\hlu\\AppData\\Local\\TidGi\\app-0.7.7-prerelease2\\resources\\node_modules\\@tiddlygit\\tiddlywiki\\boot\\boot.js","C:\\Users\\hlu\\AppData\\Local\\TidGi\\app-0.7.7-prerelease2\\resources\\app.asar.unpacked\\.webpack\\main\\543.index.worker.js"]}

node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- C:\Users\hlu\AppData\Local\TidGi\app-0.7.7-prerelease2\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js
- C:\Users\hlu\AppData\Local\TidGi\app-0.7.7-prerelease2\resources\app.asar.unpacked\.webpack\main\543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.$tw.modules.execute (C:\Users\hlu\AppData\Local\TidGi\app-0.7.7-prerelease2\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:867:11)
    at require (C:\Users\hlu\AppData\Local\TidGi\app-0.7.7-prerelease2\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:826:24)
    at $:/plugins/linonetwo/smart-field/form.js:1:26
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)[0m

```

---

**Comment by linonetwo** [comment]
把 tw-react 插件也装上哈

**Comment by linonetwo** [comment]
prerequisite of this plugin is tw-react.
