### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by Clear8Heart** [tiddly-gittly/TidGi-Desktop#240]
## Environment

TidGi 0.7.7
Electron 18.2.0
win32 10.0.22000
Locale: zh-CN

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\koms0\\Desktop\\TiddlyWiki\\Wiki\\Wiki","branch":"main","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: fatal: unable to access 'https://github.com/Clear8Heart/Wiki/': Failed to connect to github.com port 443: Timed out
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\koms0\\Desktop\\TiddlyWiki\\Wiki\\Wiki","branch":"main","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: fatal: unable to access 'https://github.com/Clear8Heart/Wiki/': Failed to connect to github.com port 443: Timed out

    at wt (C:\Users\koms0\AppData\Local\TidGi\app-0.7.7\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5Csync.js:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at StartConfiguringGithubRemoteRepository (C:\Users\koms0\AppData\Local\TidGi\app-0.7.7\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CcommitAndSync.js:85:13)
    at Pt (C:\Users\koms0\AppData\Local\TidGi\app-0.7.7\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CinitGit.js:37:25)
```

---

**Comment by linonetwo** [comment]
accessToken 没填吧

**Comment by linonetwo** [comment]
试试最新的预发版 [https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2) ， 先创建本地版，之后在配置里再开启同步，创建成功率更高。
