### ISSUE TITLE
bug: E-4 你启动了同一个Wiki两次，这可能是程序bug导致的。 E:\taiji_wiki\wiki

### ISSUE THREAD

**Issue by jesee030** [tiddly-gittly/TidGi-Desktop#253]
## Environment

TidGi 0.7.7
Electron 18.2.0
win32 10.0.19044
Locale: zh-CN

## Description:

{"type":"running","uid":1,"resultType":"observable"}
{"type":"result","uid":1,"payload":{"type":"control","actions":"tw-start"}}
{"type":"result","uid":1,"payload":{"type":"stdout","message":" syncer-server-filesystem: Dispatching 'save' task: $:/StoryList \n"}}
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 
{"type":"result","uid":1,"payload":{"type":"stdout","message":"Serving on http://0.0.0.0:5212\n"}}
Serving on http://0.0.0.0:5212
{"type":"result","uid":1,"payload":{"type":"stdout","message":"(press ctrl-C to exit)\n"}}
(press ctrl-C to exit)
{"type":"result","uid":1,"payload":{"type":"control","actions":"tw-booted","message":"Tiddlywiki booted at http://0.0.0.0:5212 (webview uri ip may be different, being getLocalHostUrlWithActualIP()) with args --listen anon-username=TidGiUser port=5212 host=0.0.0.0 root-tiddler=$:/core/save/lazy-images"}}
{"type":"result","uid":1,"payload":{"type":"stdout","message":" syncer-server-filesystem: Dispatching 'save' task: $:/StoryList \n"}}
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 

## Additional Context

```typescript
E-4 重复启动维基错误: E-4 你启动了同一个Wiki两次，这可能是程序bug导致的。 E:\taiji_wiki\wiki
    at aa.startWiki (C:\Users\keyter\AppData\Local\TidGi\app-0.7.7\resources\app.asar\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Csrc%5Cservices%5Cwiki%5Cindex.ts:88:13)
    at aa.wikiStartup (C:\Users\keyter\AppData\Local\TidGi\app-0.7.7\resources\app.asar\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Csrc%5Cservices%5Cwiki%5Cindex.ts:547:20)
    at Ra.wikiFolderLocation [as initializeWorkspaceView] (C:\Users\keyter\AppData\Local\TidGi\app-0.7.7\resources\app.asar\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Csrc%5Cservices%5CworkspacesView%5Cindex.ts:99:18)
    at C:\Users\keyter\AppData\Local\TidGi\app-0.7.7\resources\app.asar\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Csrc%5Cservices%5CworkspacesView%5Cindex.ts:50:53
```

---

**Comment by linonetwo** [comment]
不知道咋触发了
