### ISSUE TITLE
bug: [1;31mError executing boot module $:/plugins/kixam/timeline/widget.timeline.js: {"code":"MODULE_NOT

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#258]
## Environment

TidGi 0.7.7
Electron 18.2.0
win32 10.0.22000
Locale: zh-CN

## Additional Context

```typescript
Error: [1;31mError executing boot module $:/plugins/kixam/timeline/widget.timeline.js: {"code":"MODULE_NOT_FOUND","requireStack":["C:\\Users\\34656\\AppData\\Local\\TidGi\\app-0.7.7\\resources\\node_modules\\@tiddlygit\\tiddlywiki\\boot\\boot.js","C:\\Users\\34656\\AppData\\Local\\TidGi\\app-0.7.7\\resources\\app.asar.unpacked\\.webpack\\main\\543.index.worker.js"]}

node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module '$:/plugins/kixam/moment/moment.js'
Require stack:
- C:\Users\34656\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js
- C:\Users\34656\AppData\Local\TidGi\app-0.7.7\resources\app.asar.unpacked\.webpack\main\543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.$tw.modules.execute (C:\Users\34656\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:867:11)
    at require (C:\Users\34656\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:826:24)
    at $:/plugins/kixam/timeline/widget.timeline.js:20:16
    at $:/plugins/kixam/timeline/widget.timeline.js:652:3
    at Script.runInContext (node:vm:139:12)[0m

```

---

**Comment by linonetwo** [comment]
插件没装

**Comment by dongrentianyu** [comment]
忘了什么时候提交的了。感觉这个插件也不常见的样子。
