### ISSUE TITLE
bug: 通过坚果云同步笔记本，在另外电脑导入这个文件夹就会出错

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#279]
### Environment 环境信息

app-0.7.9/

### Description 描述

Unhandled Promise Rejection
Error: mainWorkspace is undefined in wikiStartup() for mainWikiPath D:/坚果云/我的坚果云/tigiwiki/卡片笔记
    at Xo.wikiStartup (C:/Users/ccnu/AppData/Local/TidGi/app-0.7.9/resources/app.asar/.webpack/main/index.js:2:1711222)
    at Fa.initializeWorkspaceView (C:/Users/ccnu/AppData/Local/TidGi/app-0.7.9/resources/app.asar/.webpack/main/index.js:2:1743495)
    at C:/Users/ccnu/AppData/Local/TidGi/app-0.7.9/resources/app.asar/.webpack/main/index.js:2:1742022

### Steps to Reproduce 复现方式

通过坚果云同步笔记本，在另外电脑导入这个文件夹就会出错

**Comment by linonetwo** [comment]
[https://github.com/tiddly-gittly/TidGi-Desktop/blob/e7fe47d362f6957ab8db6d7fd4593c911dc4f108/src/services/wiki/index.ts#L570](https://github.com/tiddly-gittly/TidGi-Desktop/blob/e7fe47d362f6957ab8db6d7fd4593c911dc4f108/src/services/wiki/index.ts#L570)

应该在前端UI就做这个检查，防止用户乱创建子知识库。可能他是想创建主知识库的。
