### ISSUE TITLE
bug: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 C:\Users\82718\iCloudDrive\onedrive\wr-wiki\wr-wiki Tid

### ISSUE THREAD

**Issue by python12345677** [tiddly-gittly/TidGi-Desktop#284]
## Environment

TidGi 0.7.7
Electron 18.2.0
win32 10.0.19044
Locale: zh-CN

## Additional Context

```typescript
Error: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 C:\Users\82718\iCloudDrive\onedrive\wr-wiki\wr-wiki Tiddlywiki booted failed with error UNKNOWN: unknown error, read Error: UNKNOWN: unknown error, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:471:19)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at Object.$tw.loadTiddlersFromFile (C:\Users\82718\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1852:13)
    at Object.$tw.loadTiddlersFromPath (C:\Users\82718\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1905:22)
    at C:\Users\82718\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1900:40
    at Object.$tw.utils.each (C:\Users\82718\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:146:12)
    at Object.$tw.loadTiddlersFromPath (C:\Users\82718\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1898:15)
    at Object.$tw.loadWikiTiddlers (C:\Users\82718\AppData\Local\TidGi\app-0.7.7\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:2201:21)
```

---

**Comment by python12345677** [comment]
删除一个出错的文件后重新导入，可以修复，貌似是和网盘冲突了。

**Comment by linonetwo** [comment]
就是坚果云盘同步后出的错是吧

**Comment by linonetwo** [comment]
出错的文件啥样，可能是云盘创建的临时文件吧

**Comment by linonetwo** [comment]
有需要就提供一下具体的 wiki 看看
