### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by zixueio** [tiddly-gittly/TidGi-Desktop#290]
## Environment

TidGi 0.7.6-prerelease2
Electron 17.0.1
win32 10.0.17763
Locale: zh-CN

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\Administrator\\Desktop\\wiki","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://github.com/zixueio/wiki'
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\Administrator\\Desktop\\wiki","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://github.com/zixueio/wiki'

    at Pt (C:\Users\Administrator\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5Csync.js:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at StartConfiguringGithubRemoteRepository (C:\Users\Administrator\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CcommitAndSync.js:82:13)
    at Mt (C:\Users\Administrator\AppData\Local\TidGi\app-0.7.6-prerelease2\resources\app.asar.unpacked\.webpack\main\file:\D:%5Ca%5CTidGi-Desktop%5CTidGi-Desktop%5Cnode_modules%5Cgit-sync-js%5Cdist%5Csrc%5CinitGit.js:37:25)
```

---

**Comment by linonetwo** [comment]
没填token吧，可以先建本地的，之后再同步上去。

**Comment by linonetwo** [comment]
试试最新的预发版 [https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2) ， 先创建本地版，之后在配置里再开启同步，创建成功率更高。
