### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by zixueio** [tiddly-gittly/TidGi-Desktop#291]
## Environment

TidGi 0.7.9
Electron 20.2.0
win32 10.0.17763
Locale: zh-CN

## Additional Context

```typescript
Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\Administrator\\Desktop\\wiki","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://github.com/zixueio/wiki'
 GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"C:\\Users\\Administrator\\Desktop\\wiki","branch":"HEAD","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: error: src refspec HEAD does not match any
error: failed to push some refs to 'https://github.com/zixueio/wiki'

    at wt (C:\Users\Administrator\AppData\Local\TidGi\app-0.7.9\resources\app.asar.unpacked\.webpack\main\722.index.worker.js:1:418240)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Et (C:\Users\Administrator\AppData\Local\TidGi\app-0.7.9\resources\app.asar.unpacked\.webpack\main\722.index.worker.js:1:420646)
    at Pt (C:\Users\Administrator\AppData\Local\TidGi\app-0.7.9\resources\app.asar.unpacked\.webpack\main\722.index.worker.js:1:422763)
```

---

**Comment by linonetwo** [comment]
没填token？

**Comment by cloudnavi** [comment]
> 没填token？

我和他一样的问题，token填了，但是错误信息里面token是空的，很奇怪

**Comment by linonetwo** [comment]
还有这里面 branch 是 HEAD 也很奇怪，反正你们都不填复现方式，我也不知道是咋回事了

**Comment by linonetwo** [comment]
用 github desktop 推上去试试吧

**Comment by cloudnavi** [comment]
> 还有这里面 branch 是 HEAD 也很奇怪，反正你们都不填复现方式，我也不知道是咋回事了，就一直没修

好吧，我没仔细看的帖子，我的是初始安装之后，第一次新建工作区WIKI的时候出的错。

**Comment by linonetwo** [comment]
试试最新的预发版 [https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2) ， 先创建本地版，之后在配置里再开启同步，创建成功率更高。
