### ISSUE TITLE
bug: Cannot read properties of null (reading 'send')

### ISSUE THREAD

**Issue by xinlivia** [tiddly-gittly/TidGi-Desktop#323]
## Environment

TidGi 0.7.13
Electron 22.0.0
win32 10.0.19044
Locale: zh-CN

## Additional Context

```typescript
TypeError: Cannot read properties of null (reading 'send')
    at C:\Users\gexin\AppData\Local\TidGi\app-0.7.13\resources\app.asar\.webpack\main\index.js:2:1715323
    at new Promise (<anonymous>)
    at da.runFilterOnWiki (C:\Users\gexin\AppData\Local\TidGi\app-0.7.13\resources\app.asar\.webpack\main\index.js:2:1715161)
    at t (C:\Users\gexin\AppData\Local\TidGi\app-0.7.13\resources\app.asar\.webpack\main\index.js:2:1715978)
    at da.syncWikiIfNeeded (C:\Users\gexin\AppData\Local\TidGi\app-0.7.13\resources\app.asar\.webpack\main\index.js:2:1716382)
    at Timeout._onTimeout (C:\Users\gexin\AppData\Local\TidGi\app-0.7.13\resources\app.asar\.webpack\main\index.js:2:1716673)
```

---

**Comment by linonetwo** [comment]
Steps to Reproduce:

**Comment by linonetwo** [comment]
估计是 

https://github.com/tiddly-gittly/TidGi-Desktop/blob/89313d5dc5b8d578751b154d692131f9858eb063/src/services/wiki/index.ts#L457

可能同步的时候，app窗口是关闭的状态
