### ISSUE TITLE
bug: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by YrracOwl** [tiddly-gittly/TidGi-Desktop#326]
### Environment 环境信息

TidGi (win32)
Version v0.7.13.

Electron Version: 22.0.0
Node Version: 16.17.1
Chromium Version: 108.0.5359.62

### Description 描述

打开的时候弹这个错误：

```
Unhandled Promise Rejection
TypeError: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:640:5)
    at C:/Users/xxx/AppData/Local/TidGi/app-0.7.13/resources/app.asar/.webpack/main/index.js:2:1699379
    at Xo.loadUrlForView (C:/Users/xxx/AppData/Local/TidGi/app-0.7.13/resources/app.asar/.webpack/main/index.js:2:1699427)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Xo.addView (C:/Users/xxx/AppData/Local/TidGi/app-0.7.13/resources/app.asar/.webpack/main/index.js:2:1699157)
    at async Promise.all (index 0)
    at Xo.addViewForAllBrowserViews (C:/Users/xxx/AppData/Local/TidGi/app-0.7.13/resources/app.asar/.webpack/main/index.js:2:1697467)
    at Ya.initializeWorkspaceView (C:/Users/xxx/AppData/Local/TidGi/app-0.7.13/resources/app.asar/.webpack/main/index.js:2:1750804)
    at C:/Users/xxx/AppData/Local/TidGi/app-0.7.13/resources/app.asar/.webpack/main/index.js:2:1748208
```

点report之后报这个错误：

```
Unhandled Promise Rejection
Error: Failed to open: ϵͳ�Ҳ���ָ�����ļ��� (0x2)
```

最新的log如下：

```
{"type":"running","uid":1,"resultType":"observable"}
{"type":"result","uid":1,"payload":{"type":"control","actions":"tw-start"}}
{"type":"result","uid":1,"payload":{"type":"stdout","message":"syncer-server-filesystem: Dispatching 'save' task: $:/StoryList\n"}}
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
{"type":"result","uid":1,"payload":{"type":"stdout","message":"Serving on http://0.0.0.0:5213\n"}}
Serving on http://0.0.0.0:5213
{"type":"result","uid":1,"payload":{"type":"stdout","message":"(press ctrl-C to exit)\n"}}
(press ctrl-C to exit)
{"type":"result","uid":1,"payload":{"type":"control","actions":"tw-booted","message":"Tiddlywiki booted at http://0.0.0.0:5213 (webview uri ip may be different, being getLocalHostUrlWithActualIP()) with args --listen anon-username=hanassel port=5213 host=0.0.0.0 root-tiddler=$:/core/save/lazy-images"}}
```

### Steps to Reproduce 复现方式

暂无

**Comment by linonetwo** [comment]
看不出是为啥，先 catch

**Comment by YrracOwl** [comment]
这个错误让我在win7上的客户端都加载不出东西了，现在一直用的网页访问的地址

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.14

**Comment by YrracOwl** [comment]
> 我等等发个包，右键图标的工作区设置里可以看到加载的 url，可以删空还原默认看看

搞定了，不过不是删空还原的。我点进去的时候里面就是默认的那个192.168.x.x:5213那个地址，没办法删空还原。然后我在浏览器里复制了另一个开启的地址进去，然后保存重启就好了。

**Comment by YrracOwl** [comment]
> > 我等等发个包，右键图标的工作区设置里可以看到加载的 url，可以删空还原默认看看
> 
> 搞定了，不过不是删空还原的。我点进去的时候里面就是默认的那个192.168.x.x:5213那个地址，没办法删空还原。然后我在浏览器里复制了另一个开启的地址进去，然后保存重启就好了。

把复位的地址改成`192.168.x.x:5213/#:`，就是不开启任何条目，而不是通过访问5213端口来重定向，会不会更好一点

**Comment by linonetwo** [comment]
按理说默认的，右键刷新一下就能好。挺奇怪的，先不管了，反正目前能解决了
