### ISSUE TITLE
bug: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 D:\BaiduNetdiskWorkspace\tiddly_backup\tidgi\empty (1) 

### ISSUE THREAD

**Issue by tupaopao999** [tiddly-gittly/TidGi-Desktop#342]
## Environment

TidGi 0.7.14
Electron 22.0.0
win32 10.0.19045
Locale: zh-CN

## Additional Context

```typescript
Error: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 D:\BaiduNetdiskWorkspace\tiddly_backup\tidgi\empty (1) (2) Tiddlywiki booted failed with error EBUSY: resource busy or locked, open 'D:\BaiduNetdiskWorkspace\tiddly_backup\tidgi\empty (1) (2)\plugins\fishing-twpub\$__language_fishing_twpubtip.tid.baiduyun.uploading.cfg' Error: EBUSY: resource busy or locked, open 'D:\BaiduNetdiskWorkspace\tiddly_backup\tidgi\empty (1) (2)\plugins\fishing-twpub\$__language_fishing_twpubtip.tid.baiduyun.uploading.cfg'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at Object.t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Object.$tw.loadTiddlersFromFile (C:\Users\旅行包\AppData\Local\TidGi\app-0.7.14\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1855:13)
    at Object.$tw.loadTiddlersFromPath (C:\Users\旅行包\AppData\Local\TidGi\app-0.7.14\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1908:22)
    at C:\Users\旅行包\AppData\Local\TidGi\app-0.7.14\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1903:40
    at Object.$tw.utils.each (C:\Users\旅行包\AppData\Local\TidGi\app-0.7.14\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:146:12)
    at Object.$tw.loadTiddlersFromPath (C:\Users\旅行包\AppData\Local\TidGi\app-0.7.14\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:1901:15)
    at Object.$tw.loadPluginFolder (C:\Users\旅行包\AppData\Local\TidGi\app-0.7.14\resources\node_modules\@tiddlygit\tiddlywiki\boot\boot.js:2053:25)
```

---

**Comment by linonetwo** [comment]
你的wiki的名字怎么这么怪啊，叫 empty (1) (2) 的

**Comment by linonetwo** [comment]
看起来是百度云在同步的时候会尝试锁住这个文件，并且给他改名加上个后缀，这就导致其他应用此时无法去读取或修改这个文件了。

这时候你稍等一会儿，等百度云同步完了，然后你右键重新载入一下应该就好了。

**Comment by linonetwo** [comment]
你看他给你改名成了 fishing-twpub\\$\_\_language\_fishing\_twpubtip.tid.baiduyun.uploading.cfg
