### ISSUE TITLE
bug: Should not crush E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"/Use

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#352]
## Environment

TidGi 0.7.15-prerelease
Electron 22.0.0
darwin 22.3.0
Locale: zh-CN

## Description:

Crush after OK
![截屏2023-02-28 23 46 09](https://user-images.githubusercontent.com/3746270/221904898-0d5c9d7b-d37a-485a-9590-5413bb67134c.png)

![截屏2023-02-28 23 46 24](https://user-images.githubusercontent.com/3746270/221904823-02ff9db9-131d-44f0-ba2f-46e386a667b6.png)

## Additional Context

```typescript
GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"/Users/linonetwo/Desktop/wiki/calendar","branch":"master","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: fatal: unable to access 'https://github.com/linonetwo/calendar/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

    at Ot (/Applications/TidGi.app/Contents/Resources/app.asar.unpacked/.webpack/main/722.index.worker.js:2:419899)
    at kt (/Applications/TidGi.app/Contents/Resources/app.asar.unpacked/.webpack/main/722.index.worker.js:2:422534)
```

---

**Comment by linonetwo** [comment]
fixed in 5ee2f583
