### ISSUE TITLE
bug: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"/Use

### ISSUE THREAD

**Issue by ming188199** [tiddly-gittly/TidGi-Desktop#356]
## Environment

TidGi 0.7.14
Electron 22.0.0
darwin 22.3.0
Locale: zh-CN

## Steps to Reproduce:

> mac电脑锁定屏幕，解锁后就会报这个错误。

## Additional Context

```typescript
GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"/Users/kk/Documents/TiddlyWiki/wiki","branch":"main","remote":"origin","userInfo":{"accessToken":""}}.
errorMessages: fatal: unable to access 'https://github.com/ming188199/wiki/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

    at Ot (/Applications/TidGi.app/Contents/Resources/app.asar.unpacked/.webpack/main/722.index.worker.js:2:419815)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at kt (/Applications/TidGi.app/Contents/Resources/app.asar.unpacked/.webpack/main/722.index.worker.js:2:422450)
```

---

**Comment by ming188199** [comment]
Failed to connect to github.com port 443 after 75022 ms: Couldn't connect to server。
看起来是github服务器不稳定造成的。
