### ISSUE TITLE
bug: E-10 Zx 代码执行服务未成功初始化，将自动尝试初始化。 

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#406]
### Environment 环境信息

Version v0.8.0-prerelease9.

Electron Version: 24.3.1
Node Version: 18.14.0
Chromium Version: 112.0.5615.183

### Description 描述

放了一天之后，zx挂了

### Steps to Reproduce 复现方式

暂不知

### Additional Context 额外上下文

[TidGi-2023-06-08.log.zip](https://github.com/tiddly-gittly/TidGi-Desktop/files/11687381/TidGi-2023-06-08.log.zip)

**Comment by linonetwo** [comment]
```
// pure nodejs context
console.log(`## Hi!`);

/** tw */

// now in worker_thread with $tw wiki access

console.log($tw.wiki.filterOperators.sum((callback) => {callback({}, '2');callback({}, '2')}))
```

```
Hi!
ReferenceError: variableMap is not defined at file:///C:/Users/LINONE~1/AppData/Local/Temp/Uo4kF9/test.mjs:7:55 at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

4

ReferenceError: variableMap is not defined evalmachine.:8 pushVariablesToTWContext(variableMap); ^ ReferenceError: variableMap is not defined at evalmachine.:8:26 at Script.runInContext (node:vm:141:12) at Object.runInContext (node:vm:291:6) at ue (C:\Users\linonetwo\AppData\Local\tidgi\app-0.8.0-prerelease10\resources\app.asar.unpacked\.webpack\main\543.index.worker.js:2:549934) at C:\Users\linonetwo\AppData\Local\tidgi\app-0.8.0-prerelease10\resources\app.asar.unpacked\.webpack\main\543.index.worker.js:2:553550 at processTicksAndRejections (node:internal/process/task_queues:95:5) SourceCode: now in worker_thread with $tw wiki access console.log($tw.wiki.filterOperators.sum((callback) => {callback({}, '2');callback({}, '2')})) pushVariablesToTWContext(variableMap);

[$:/state/linonetwo/zx-script/output/test](http://192.168.3.6:5215/#%24%3A%2Fstate%2Flinonetwo%2Fzx-script%2Foutput%2Ftest)
```
