### ISSUE TITLE
bug: Failed to register protocol: filefix

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#422]
## Environment

TidGi 0.8.0-prerelease15
Electron 25.1.1
darwin 22.5.0
Locale: zh-CN

## Additional Context

```typescript
Error: Failed to register protocol: filefix
    at Object.c.handle (node:electron/js2c/browser_init:2:58157)
    at /Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1939172
    at Sl (/Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1939945)
    at Tl.addView (/Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1953975)
    at /Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1952264
    at async Promise.all (index 1)
    at Tl.addViewForAllBrowserViews (/Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1952158)
    at /Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2093728
    at async Promise.all (index 1)
    at Bh.initializeWorkspaceView (/Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2093524)
    at /Applications/TidGi.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2092578
```

---

[TidGi-2023-06-21.log.zip](https://github.com/tiddly-gittly/TidGi-Desktop/files/11814939/TidGi-2023-06-21.log.zip)

**Comment by linonetwo** [comment]
好像是因为

```
view.webContents.session.protocol.handle('filefix', async (request)
```

本质上是会给所有 view 同时注册，所以第二个工作区的 view 也会被这样注册一次，就出现重复了。

解决方法是先检测一下

```
if (!view.webContents.session.protocol.isProtocolHandled('filefix')) {
```
