### ISSUE TITLE
bug: Cannot read properties of null (reading 'send')

### ISSUE THREAD

**Issue by xinlivia** [tiddly-gittly/TidGi-Desktop#425]
## Environment

TidGi 0.7.14
Electron 22.0.0
win32 10.0.19045
Locale: zh-CN

## Additional Context

```typescript
TypeError: Cannot read properties of null (reading 'send')
    at C:\Users\gexin\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1716465
    at new Promise (<anonymous>)
    at ma.runFilterOnWiki (C:\Users\gexin\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1716303)
    at t (C:\Users\gexin\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1717132)
    at ma.syncWikiIfNeeded (C:\Users\gexin\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1717536)
    at Timeout._onTimeout (C:\Users\gexin\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1717827)
```

---

**Comment by linonetwo** [comment]
0.8.0 出了

**Comment by linonetwo** [comment]
官网的还没更新，先从 Github Release 里下吧
