### ISSUE TITLE
bug: Error executing boot module $:/plugins/linonetwo/tw-react/example.js:

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#459]
### Environment 环境信息

Version v0.8.1-prerelease6

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Description 描述

Unhandled Promise Rejection
Error: [1;31mError executing boot module $:/plugins/linonetwo/tw-react/example.js: {"code":"MODULE_NOT_FOUND","requireStack":["C://Users//34656//AppData//Local//tidgi//app-0.8.1-prerelease6//resources//node_modules//@tiddlygit//tiddlywiki//boot//boot.js","C://Users//34656//AppData//Local//tidgi//app-0.8.1-prerelease6//resources//app.asar.unpacked//.webpack//main//543.index.worker.js"]}
Error: Cannot find module 'react'
Require stack:
- C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js
- C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar.unpacked/.webpack/main/543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at a (C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar.unpacked/.webpack/main/543.index.worker.js:2:448146)
    at Object.$tw.modules.execute (C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:893:11)
    at require (C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:852:24)
    at $:/plugins/linonetwo/tw-react/example.js:6:20
    at $:/plugins/linonetwo/tw-react/example.js:61:4
    at Object.$tw.utils.evalGlobal (C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:617:12)[0m
    at Object.next (C:/Users/34656/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar/.webpack/main/index.js:2:1955845)

### Steps to Reproduce 复现方式

检查之后发现是因为meta文件导致的。我删除了tw-react的meta文件之后就能正常启动了。但奇怪的是，目前只发现这一个wiki有这样的问题，其他的wiki并没有出现这样的问题。

### Additional Context 额外上下文

[TidGi-2023-07-27.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/12178894/TidGi-2023-07-27.log)

看样子是tw-react插件出了问题，但昨天用的还好好的。而且也没更新这个插件。不知道为什么出了问题。

**Comment by linonetwo** [comment]
没事，知道修复方法就好了，这也是玄学

**Comment by linonetwo** [comment]
反正发在这里让之后的人能搜到就行了
