### ISSUE TITLE
bug: compatibility with plugin:left open tab:"Global assignment is not allowed within modules on node."

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#460]
### Environment 环境信息

after install the plugin:left open tab
```
Unhandled Promise Rejection
Error: [1;31mError executing boot module $:/plugins/felixhayashi/tiddlymap/js/config/vis: {"code":"MODULE_NOT_FOUND","requireStack":["C://Users//11507//AppData//Local//tidgi//app-0.8.1-prerelease6//resources//node_modules//@tiddlygit//tiddlywiki//boot//boot.js","C://Users//11507//AppData//Local//tidgi//app-0.8.1-prerelease6//resources//app.asar.unpacked//.webpack//main//543.index.worker.js"]}
Error: Cannot find module '$:/plugins/felixhayashi/vis/vis.js'
Require stack:
- C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js
- C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar.unpacked/.webpack/main/543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at a (C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar.unpacked/.webpack/main/543.index.worker.js:2:448146)
    at Object.$tw.modules.execute (C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:893:11)
    at require (C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:852:24)
    at $:/plugins/felixhayashi/tiddlymap/js/config/vis:3:80
    at $:/plugins/felixhayashi/tiddlymap/js/config/vis:14:4
    at Object.$tw.utils.evalGlobal (C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:617:12)[0m
    at Object.next (C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar/.webpack/main/index.js:2:1955845)
```

after install plugin: felixhayashi/vis
```
Unhandled Promise Rejection
Error: [1;31mError executing boot module $:/plugins/felixhayashi/vis/vis.js: "Global assignment is not allowed within modules on node."
undefined[0m
    at Object.next (C:/Users/11507/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar/.webpack/main/index.js:2:1955845)
```

### Steps to Reproduce 复现方式

install plugin: felixhayashi/vis

**Comment by linonetwo** [comment]
据说已经修好了 https://github.com/tiddly-gittly/TidGi-Desktop/issues/385

**Comment by heavenkiller2018** [comment]
I'm afraid not yet in the newest TidGi version ! 

```
Version v0.8.1-prerelease6

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134
```

**Comment by linonetwo** [comment]
Still have error `Warning: Global assignment detected [ 'core-js_shared' ]`

I think this should be a bug in the tiddlymap's build and its developer should be told to go with https://github.com/tiddly-gittly/Modern.TiddlyDev
