### ISSUE TITLE
bug: Object has been destroyed

### ISSUE THREAD

**Issue by king0billy** [tiddly-gittly/TidGi-Desktop#489]
## Environment

TidGi 0.8.0
Electron 25.2.0
win32 10.0.22621
Locale: zh-CN

## Additional Context

```typescript
TypeError: Object has been destroyed
    at C:\Users\22427\AppData\Local\tidgi\app-0.8.0\resources\app.asar\.webpack\main\index.js:2:1960707
```

---

**Comment by linonetwo** [comment]
看不出原因

**Comment by king0billy** [comment]
这个bug是我点了一个按钮自动提交的，暂时无法复现。下面是一个新bug
导出所有条目-》静态html-》报错
内部的 JavaScript 错误
喔，真是令人尴尬。建议刷新您的浏览器，重新启动 TiddlyWiki
Uncaught TypeError: parent.append is not a function

**Comment by king0billy** [comment]
还有一个bug  Version v0.8.1-prerelease6  每次打开都提示cpl更新插件 更新后关闭tidgi再打开 还是提示更新相同的插件

**Comment by king0billy** [comment]
> 还有一个bug Version v0.8.1-prerelease6 每次打开都提示cpl更新插件 更新后关闭tidgi再打开 还是提示更新相同的插件

点击“保存” 即sycn from tidgi main process无反应

**Comment by king0billy** [comment]
> 看不出原因，不过应该不影响使用！
每次通过cpl更新插件或重新安装都会出错，完全卸载了tidgi重装也一样！

**Comment by king0billy** [comment]
插件的json文件已经保存在wiki/tiddlers路径下，但是每次重启服务都显示空白需要重新安装

**Comment by dongrentianyu** [comment]
并且太记最新版本应该是Version v0.8.1-prerelease6，你可以试试最新版本的太记。

**Comment by king0billy** [comment]
> [插件更新后重启又要更新](https://tw-cn.netlify.app/#%E6%8F%92%E4%BB%B6%E6%9B%B4%E6%96%B0%E5%90%8E%E9%87%8D%E5%90%AF%E5%8F%88%E8%A6%81%E6%9B%B4%E6%96%B0)
> 
> 可查看这个链接排查，简单来说就是把插件的meta文件删除。
> 
> ![image](https://private-user-images.githubusercontent.com/109711900/287496901-78d9753d-b0ad-4f6b-b8ee-285a03b5f421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTM5NjEsIm5iZiI6MTcwMTU5MzY2MSwicGF0aCI6Ii8xMDk3MTE5MDAvMjg3NDk2OTAxLTc4ZDk3NTNkLWIwYWQtNGY2Yi1iOGVlLTI4NWEwM2I1ZjQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwODU0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODYwOTMxMjVmMGQxZGFjNTc1Njg4OGY4OGFmMTIxYzlmNmM1ZTBhM2EwOWY0ZGMzMjBjZmNkZjc2NWNkMWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n36LUkBVdVaJ3xmtlrbHTMGQvJZh4l95aW9m9iF8jQI)


十分有用，谢谢！

**Comment by king0billy** [comment]
> 并且太记最新版本应该是Version v0.8.1-prerelease6，你可以试试最新版本的太记。

已经在用这个最新版本的TidGi了  还有一个问题  导出所有条目-》静态html-》报错
内部的 JavaScript 错误
喔，真是令人尴尬。建议刷新您的浏览器，重新启动 TiddlyWiki
Uncaught TypeError: parent.append is not a function
未捕获的 TypeError：parent.append 不是函数
`boot.js:214 Uncaught TypeError: parent.append is not a function
$tw.utils.error @ boot.js:214
widget.js:50 Uncaught TypeError: parent.append is not a function
    at SlateWriteWidget.render (widget.js:50:12)
    at Widget.renderChildren (widget.js:599:15)
    at SetWidget.render (set.js:35:7)
    at Widget.renderChildren (widget.js:599:15)
    at TranscludeWidget.render (transclude.js:35:7)
    at Widget.renderChildren (widget.js:599:15)
    at RevealWidget.render (reveal.js:48:7)
    at Widget.renderChildren (widget.js:599:15)
    at ImportVariablesWidget.render (importvariables.js:35:7)
    at Widget.renderChildren (widget.js:599:15)`

**Comment by king0billy** [comment]
> 如果有些导出的条目含有echarts的widget，是会有这个问题的

那怎么知道哪些条目有echarts的widget呀

**Comment by dongrentianyu** [comment]
这报错还有`SlateWriteWidget`，可能所见即所得插件也要禁用。你可以删除这个插件试试。我刚刚在自己的wiki里导出所有条目，选择静态html，没有问题是正常生成的。不过一般来说不会用到导出所有条目的功能吧。

**Comment by king0billy** [comment]
> 这报错还有`SlateWriteWidget`，可能所见即所得插件也要禁用。你可以删除这个插件试试。我刚刚在自己的wiki里导出所有条目，选择静态html，没有问题是正常生成的。不过一般来说不会用到导出所有条目的功能吧。

我想要导出的是像教程那样的完整网页 怎么导出呀

**Comment by king0billy** [comment]
> 你是要发布wiki成博客吗？
> 
> 具体参考[纠正错误太记发布网址的方式](https://www.bilibili.com/video/BV1uD4y1H7ri/)视频教程。
> 
> 如果不是发布到网络上的话，可以保存一份html文件下来。点击一个云的图标，点击第二个就会弹出保存页面了。

问题解决了 万分感谢！

**Comment by king0billy** [comment]
> 你是要发布wiki成博客吗？
> 
> 具体参考[纠正错误太记发布网址的方式](https://www.bilibili.com/video/BV1uD4y1H7ri/)视频教程。
> 
> 如果不是发布到网络上的话，可以保存一份html文件下来。点击一个云的图标，点击第二个就会弹出保存页面了。

你知道这个问题怎么解决吗  
https://github.com/tiddly-gittly/tw-mobile-sync/issues/32#issue-1898235539
