### ISSUE TITLE
bug: 子知识库出现在了发布的主知识库中

### ISSUE THREAD

**Issue by wsqstar** [tiddly-gittly/TidGi-Desktop#516]
### Environment 环境信息

TidGi (win32)
Version v0.9.1

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

### Description 描述

根据描述，应该是![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/24500520/e48bbd37-ac80-4201-9bf6-f7c2fe6e3627)
但是
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/24500520/16035e21-9d0e-47ce-8e61-f4cba4961f04)
发布之后是可以直接访问的……
https://tidy.1314.io/#%E6%B5%8B%E8%AF%95%E7%A7%81%E6%9C%89:%E6%B5%8B%E8%AF%95%E7%A7%81%E6%9C%89%20Index

### Steps to Reproduce 复现方式

- 按照教程创建子知识库
- 直接出现此问题

**Comment by linonetwo** [comment]
注意看 FileSystempath 这个 tid，你看看里面是不是配错了

还有你有把 private 小写的这个标签，配到子工作区设置里吗？

**Comment by wsqstar** [comment]
作为一个从太记尝试直接入门太微的，重新按照指南，新建一个子工作区测试了一下。

- GitHub ：  https://github.com/wsqstar/tidgi-wiki/commit/863720dd68dda676c2e337a615be4d4811678292
- 结果https://tidy.1314.io/#%E6%B5%8B%E8%AF%95%E7%A7%81%E6%9C%89:%E6%B5%8B%E8%AF%95%E7%A7%81%E6%9C%89%20Index
-
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/24500520/d8a36c23-11ff-49c5-a99e-43c1f3f3f232)

**Comment by wsqstar** [comment]
[补充参考的文档](https://tiddly-wiki-chinese-tutorial.vercel.app/#%24%3A%2FImport:%24%3A%2FImport%20%E5%A4%AA%E8%AE%B0%E6%98%AF%E5%A6%82%E4%BD%95%E5%81%9A%E6%9C%AC%E5%9C%B0%E6%8C%81%E4%B9%85%E5%8C%96%E7%9A%84%20%E5%A4%AA%E8%AE%B0%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-%E5%BC%80%E7%9D%80%E4%BB%A3%E7%90%86502%E6%88%AA%E5%9B%BE.png%20%E5%A4%AA%E8%AE%B0%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20%E4%BD%BF%E7%94%A8%E5%A4%AA%E8%AE%B0%E5%92%8CGithub%E6%A1%8C%E9%9D%A2%E7%89%88%E6%8E%92%E6%9F%A5%E9%97%AE%E9%A2%98%20%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E5%A4%AA%E5%BE%AE%EF%BC%81:~:text=%E7%A7%81%E6%9C%89%E5%86%85%E5%AE%B9-,%E4%B8%8A%E9%9D%A2%E8%AF%B4%E7%9A%84%E5%B7%A5%E4%BD%9C%E5%8C%BA%E7%A7%B0%E4%B8%BA%E4%B8%BB%E5%B7%A5%E4%BD%9C%E5%8C%BA%EF%BC%8C%E8%BF%98%E6%9C%89%E4%B8%80%E7%A7%8D%E5%AD%90,%E6%8A%8A%E5%8A%A0%E4%BA%86%20%E3%80%8CPrivate%E3%80%8D%20%E6%A0%87%E7%AD%BE%E7%9A%84%E6%9D%A1%E7%9B%AE%E5%8F%8A%E5%85%B6%E5%AD%90%E6%9D%A1%E7%9B%AE%E8%87%AA%E5%8A%A8%E6%94%BE%E8%BF%9B%E5%8E%BB%E3%80%82,-%E5%89%8D%E7%AB%AF%E5%92%8C%E7%A1%AC%E7%9B%98)
关于FileSystempath 这部分不太熟悉 但是确实按照文档执行了

**Comment by linonetwo** [comment]
配到子工作区设置里

估计你漏了这个

**Comment by linonetwo** [comment]
还有这个不确定现在有没有bug，你得看FileSystempath 这个 tid，你看看里面是不是配错了

**Comment by wsqstar** [comment]
关于子工作区设置，我尝试了两种方案，

1. 创建时，不配置tag，等一下配置（已经配置
2. 创建时直接配置tag
目前都没有效果。
我这就去看看FileSystempath

**Comment by wsqstar** [comment]
这是我现在的FileSystempath.tid 不知道能帮忙看看和正常的有什么区别吗 https://github.com/wsqstar/tidgi-wiki/blob/main/tiddlers/FileSystemPaths.tid

**Comment by wsqstar** [comment]
我先看一下大佬的视频 看看是不是有区别 https://www.bilibili.com/video/BV1jo4y1H7d3/

**Comment by linonetwo** [comment]
应该没问题，加了 private-new 会放入 private-shiqi-new 文件夹里。

不过 kin::to 需要装 kin-filter 插件。这个好像现在去掉了，你得手动装一下。下个版本我修复一下，改成另一个写法，类似我的 https://github.com/linonetwo/wiki/blob/dc5e7950a5e05085a62e62436b8a7fe982129e19/tiddlers/FileSystemPaths.tid#L5

**Comment by linonetwo** [comment]
你可以自己先改成我的这种写法

**Comment by wsqstar** [comment]
get 了解了！ 对了 重启的时候报错 昨天就有了 Unhandled Promise Rejection
RangeError: Maximum call stack size exceeded
    at BrowserWindow.emit (node:events:529:35)
    at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
    at App.<anonymous> (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
    at App.emit (node:events:517:28)
    at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
    at App.<anonymous> (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
    at App.emit (node:events:517:28)
    at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
    at App.<anonymous> (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
    at App.emit (node:events:517:28)
    at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
    at App.<anonymous> (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
    at App.emit (node:events:517:28)
    at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
    at App.<anonymous> (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
    at App.emit (node:events:517:28)

**Comment by linonetwo** [comment]
新问题开个新issue吧，不然关了这个issue就不会修另一个了
