### ISSUE TITLE
bug: Error when processing tiddler {  title: '2024-01-25T14:00:00+08:00',  created: '20240125072421968'

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#517]
### Description 描述

```
Error when processing tiddler { title: '2024-01-25T14:00:00+08:00', created: '20240125072421968', creator: '林一二', startDate: '20240125060000000', endDate: '20240125071500000', 'draft.title': '', calendarEntry: 'yes', tags: '解决程序bug', modified: '20240125072435840', modifier: '林一二', caption: '修sp的重试次数的问题', type: 'text/vnd.tiddlywiki', text: '' } TypeError: Cannot read properties of undefined (reading 'fields') at $:/plugins/linonetwo/tw-mobile-sync/server-sync-v1-endpoint.js:10:153 at Array.forEach (<anonymous>) at Object.handler2 [as handler] ($:/plugins/linonetwo/tw-mobile-sync/server-sync-v1-endpoint.js:9:1224) at IncomingMessage.<anonymous> ($:/core/modules/server/server.js:308:10) at IncomingMessage.emit (node:events:517:28) at endReadableNT (node:internal/streams/readable:1368:12) at processTicksAndRejections (node:internal/process/task_queues:82:21)

```

### Steps to Reproduce 复现方式

手机端新建日历项目，同步到电脑端导致的

**Comment by linonetwo** [comment]
fixed in e43e3ec7fe3557890aa6e2c04707c7699be548f5
