### ISSUE TITLE
bug: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by wsqstar** [tiddly-gittly/TidGi-Desktop#518]
### Environment 环境信息

TidGi (win32)
Version v0.9.1

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

### Description 描述

 Unhandled Promise Rejection
RangeError: Maximum call stack size exceeded
at BrowserWindow.emit (node:events:529:35)
at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
at App. (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
at App.emit (node:events:517:28)
at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
at App. (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
at App.emit (node:events:517:28)
at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
at App. (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
at App.emit (node:events:517:28)
at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
at App. (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
at App.emit (node:events:517:28)
at Zu.clearWindowsReference (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4418339)
at App. (C:/Users/wsq_s/AppData/Local/tidgi/app-0.9.1/resources/app.asar/.webpack/main/index.js:2:4540721)
at App.emit (node:events:517:28)

### Steps to Reproduce 复现方式

只要关闭了主页面，就会弹窗。但是不影响其他使用。

**Comment by linonetwo** [comment]
应该是太记小窗的bug，我最近没有那个就没发现，下个版本修一下
