### ISSUE TITLE
bug: mobile sync 同步后，工作区打不开

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#561]
### Steps to Reproduce 复现方式

切换工作区再切换回来，会展示 mobile sync 相关报错， 好像是误识别为了网页加载报错，所以展示了报错页面，没展示webview

**Comment by linonetwo** [comment]
```
Wiki 页面未成功启动或未成功加载
Error when processing tiddler { title: '2024-05-24T15:00:00+08:00', created: '20240524081954357', creator: '林一二', startDate: '20240524070000000', endDate: '20240524081500000', calendarEntry: 'yes', tags: '项目管理', modified: '20240524101916991', modifier: '林一二', caption: '讨论', type: 'text/vnd.tiddlywiki', text: '' } Error: Unknown call format to make() at make ($:/plugins/linonetwo/tw-mobile-sync/server-sync-v1-endpoint.js:1:19900) at mergeTiddler ($:/plugins/linonetwo/tw-mobile-sync/server-sync-v1-endpoint.js:1:25987) at $:/plugins/linonetwo/tw-mobile-sync/server-sync-v1-endpoint.js:9:1558 at Array.forEach (<anonymous>) at Object.handler2 [as handler] ($:/plugins/linonetwo/tw-mobile-sync/server-sync-v1-endpoint.js:9:1426) at IncomingMessage.<anonymous> ($:/core/modules/server/server.js:308:10) at IncomingMessage.emit (node:events:514:28) at endReadableNT (node:internal/streams/readable:1408:12) at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
